### ISSUE TITLE
VS crash when using pencil

### ISSUE THREAD

**Issue by Eurikon** [imaginando/imaginando.github.io#23]
Hello,

I don't see a proper section to open an issue for VS. 

I just want to let you know that when using the application on Mac OS (M1). 

While having the sidecar function enabled and the iPad as second screen.
After I drag VS to the iPad screen and click it with Apple Pencil, the application will crash. 

I can repeat this process, with same outcome.

**Comment by sinosoidal** [comment]
@Eurikon this will be moved to our internal repository. Will close the issue here. Thanks for the report.

**Comment by Eurikon** [comment]
Ok noted thanks, can you please update this thread once this is fixed? 
Take care
