### ISSUE TITLE
LK help contents sidebar missing 'Setup' page link

### ISSUE THREAD

**Issue by EvilClivE** [imaginando/imaginando.github.io#3]
![LK_docs_menu](https://user-images.githubusercontent.com/22507346/77745563-676b5b80-7013-11ea-80d9-7ce42ae13b64.png)

**Comment by joselcvarela** [comment]
@EvilClivE also we were missing "patches" on DRC
Fixed here:
https://github.com/imaginando/imaginando.github.io/commit/d3ec071bcfbb3fd9fd31538c7fefd2a0492f7c17
